ci-fix: use proper format for printing enum value
Introduced in the last iteration (v4) by mistake, commit
bd195d3f76f115

    usb-device-manager.c: In function ‘channel_event’:
    usb-device-manager.c:900:19: error: format ‘%d’ expects argument of
    type ‘int’, but argument 4 has type ‘unsigned int’ [-Werror=format=]

    g_warning("Unhandled SpiceChannelEvent %d, disconnecting usbredir %p", event, channel);
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~
    /usr/include/glib-2.0/glib/gmessages.h:339:32: note: in definition of macro ‘g_warning’
                                    __VA_ARGS__)
                                    ^~~~~~~~~~~

Also removes extra space.

Signed-off-by: Victor Toso <victortoso@redhat.com>
Acked-by: Frediano Ziglio <fziglio@redhat.com>